### ISSUE TITLE
not better than async in http request

### ISSUE THREAD

**Issue by superlbr** [suguru03/aigle#110]
node v 12.6.0

try 50 request, 3 times.

async (5408 + 5260 + 5342) / 3 = 5336.67ms
aigle (5550 + 5297 + 5429) / 3 = 5425.33ms

code like this
```
const promiseMapLimit = promisify(async.mapLimit)
// await Aigle.maplimit(urls, 5, async function(url) {
await promiseMapLimit(urls, 5, async function(url) {
     await curl(url)
     ...
```

**Comment by suguru03** [comment]
Hi @superlbr! 
Thanks for the issue!

Your test case relies on the HTTP requests. HTTP requests are much slower than the execution of functions, so we can't know which one is faster.

So, I added [a benchmark test](https://github.com/suguru03/aigle/commit/b7287ded542d733831efcdee9a44cd76a5f1a45b) for the async library. 

`Aigle.mapLimit` seems to be faster than `async.mapLimit`.

Node version: v12.7.0
```sh
$ node ./benchmark -t mapLimit:array:async

======================================
[Aigle] v1.14.1
[async] v3.1.0
======================================
[mapLimit:array:async] Executing...
[1] "aigle" 7.64μs[1.00][1.00]
[2] "async" 20.7μs[0.369][2.71]
```

Also, when you use the async library with async functions, you can simply call the functions without callback. 😄 
```js
await async.mapLimit(urls, 5, async function(url) { ... })
```

**Comment by superlbr** [comment]
yeah, difference on μs level could be ignored on the HTTP requests.
there must exist a fastest npm module optimized for http request, I just didn't find yet.

**Comment by suguru03** [comment]
I will close the issue. 🙂
