### ISSUE TITLE
Missing symbols for replacing global Promise in TypeScript

### ISSUE THREAD

**Issue by tynor** [suguru03/aigle#140]
When attempting to replace the global `Promise` constructor with Aigle in TypeScript, I'm running into compilation errors regarding missing symbols on both the Aigle constructor and Aigle instances.

`package.json`:
```json
{
  "name": "tmp.WHQVCnJ3",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@types/node": "^14.14.10",
    "typescript": "^4.1.2"
  },
  "dependencies": {
    "aigle": "^1.14.1"
  }
}
```

`index.ts`:
```typescript
import Aigle from 'aigle';
global.Promise = Aigle;

const foo: Promise<number> = Aigle.resolve(10);
```

Output from `yarn tsc index.ts`:
```
index.ts:2:1 - error TS2741: Property '[Symbol.species]' is missing in type 'typeof Aigle' but required in type 'PromiseConstructor'.

2 global.Promise = Aigle;
  ~~~~~~~~~~~~~~

  .yarn/cache/typescript-patch-c1223b1b1d-001ab09bb8.zip/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts:178:14
    178     readonly [Symbol.species]: PromiseConstructor;
                     ~~~~~~~~~~~~~~~~
    '[Symbol.species]' is declared here.

index.ts:4:7 - error TS2741: Property '[Symbol.toStringTag]' is missing in type 'Aigle<number>' but required in type 'Promise<number>'.

4 const foo: Promise<number> = Aigle.resolve(10);
        ~~~

  .yarn/cache/typescript-patch-c1223b1b1d-001ab09bb8.zip/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts:174:14
    174     readonly [Symbol.toStringTag]: string;
                     ~~~~~~~~~~~~~~~~~~~~
    '[Symbol.toStringTag]' is declared here.


Found 2 errors.
```

I couldn't get Aigle working off master branch, but I came up with nothing on a quick search through the repository for "species" and "toStringTag".

**Comment by suguru03** [comment]
@tynor Thanks for the issue!
I will take a look. 🙂

**Comment by suguru03** [comment]
@tynor I checked the `global.Promise` type definition. 
`PromiseConstructor` doesn't allow `PromiseLike` and restricts that all methods need to return `Promise` instancies.

`Aigle` implements `PromiseLike` and returns `Aigle` instancies. So you can't assign `Aigle` to `global.Promise` without as any. (You could override the global `Promise` type definition if you really need.)

```ts
import Aigle from 'aigle';
global.Promise = Aigle as any;
```

```ts
const foo: Promise<number> = Aigle.resolve(10); // doesn't work, because Aigle doesn't extend Promise
const foo: Aigle<number> = Aigle.resolve(10); // works
const foo: PromiseLike<number> = Aigle.resolve(10); // works
 ```

Adding the `Symbol.species` handling doesn't help the issue, but I added it on https://github.com/suguru03/aigle/pull/141, thanks! 😄

**Comment by tynor** [comment]
@suguru03 Thanks for taking a look! I'll go bug libraries I use to use `PromiseLike`. :)
