### ISSUE TITLE
Collection uniformity

### ISSUE THREAD

**Issue by Kikobeats** [suguru03/aigle#24]
I was checking about `Aigle.parallel` and I found at least exist 3 methods for do technically the same, but using different input. Specifically I'm referrencing this methods:

```
- Aigle.all
- Aigle.props
```

That basically could be expose just in one

```
- Aigle.parallel
```

The think I'm suggesting is avoid expose overhead methods for make easy use the same method all the time, because:

- Technically doing the same, so input is a implementation detail.
- Less methods to learn.
- Tiny API.

For example, taking lodash as example, see [lodash.forEach](https://lodash.com/docs/4.17.4#forEach) method. You can use it for objects or arrays, and it's so powerful; the point is it is not distinguishing between two methods; just one for `Collection` an abstraction of data type that include `array` and `object` (like `Iterable`).

What do you think?

**Comment by suguru03** [comment]
> Aigle.all

It is the same functionality as a native `Promise.all`. It always returns an array, Aigle has to keep it.

> Aigle.props

It is the same functionality as `Bluebird.props`, it always returns an object. The library also considers Bluebird users.

> Aigle.parallel

It has both functionalities. Also, it is almost the same as `Async.parallel`. 

> Less methods to learn.

If I remove `all` and `props`, Promise users need to learn `parallel`, also if I remove `parallel`, Async users need to lean `all` and `props`. Therefore I made three APIs.

**Comment by Kikobeats** [comment]
> Aigle.parallel: It has both functionalities.

Then using `.parallel` could be enough?

**Comment by suguru03** [comment]
Yes, it is enough. But I don't want to delete `all` and `props` because of the reasons.

**Comment by Kikobeats** [comment]
Another question: `Aigle.map === Aigle.all === Promise.all` ?

**Comment by suguru03** [comment]
Hi, @Kikobeats !
`Aigle.all` is the same functionality as `Promise.all`.
`Aigle.map` is similar to `Array#map` and `Lodash.map`, but you can take an async iterator as a second argument.
