### ISSUE TITLE
mixin lodash _.chain().value() not work

### ISSUE THREAD

**Issue by HoKangInfo** [suguru03/aigle#33]
const _ = require('lodash');
const Aigle = require('aigle');
Aigle.mixin(_);

function asyncFunc(n) {
  return new Promise(resolve => setTimeout(resolve, 10, n * 2));
}

main=async function() {
// example 1
const array = [1, 2, 3];
const result_1 = await Aigle.map(array, asyncFunc);

// example 2
const result_2 = await Aigle.chain(array)
  .map(asyncFunc)
  .sum()
  .value();
// or
const result_3 = await Aigle.resolve(array)
  .map(asyncFunc)
  .sum();

const result_4 = await Aigle.map(array, asyncFunc)
  .sum();

console.log(result_1,result_2,result_3,result_4)
}()
// ==> [ 2, 4, 6 ] undefined 12 12
// should result_2 == result_4 
├─┬ aigle@1.9.1
│ └── aigle-core@1.0.0
├── lodash@4.17.4

**Comment by HoKangInfo** [comment]
├─┬ aigle@1.8.1
│ └── aigle-core@1.0.0
├── lodash@4.17.4
// ==> [ 2, 4, 6 ] 12 12 12
├─┬ aigle@1.9.0
│ └── aigle-core@1.0.0
├── lodash@4.17.4
// ==>[ 2, 4, 6 ] undefined 12 12

**Comment by suguru03** [comment]
Thank you for the issue.
I deleted the value on [this commit](https://github.com/suguru03/aigle/commit/5590b680645684b680eb4903e2f6a24ae6db620f#diff-aa4b525a56a91e44b0a2a319d55e8c1b), but I think it should have the value.

I'll revert the changes, thanks 😄

**Comment by HoKangInfo** [comment]
THX, You did what I needed.
I use lodash and async. now, i can use Aigle every place.

**Comment by suguru03** [comment]
@HoKangInfo 
I just published it on v1.9.2!
Thanks for using Aigle, I'm really grateful! 😄
