### ISSUE TITLE
aigle mixin lodash use chain thru get diff result

### ISSUE THREAD

**Issue by HoKangInfo** [suguru03/aigle#36]
const _ = require('lodash');
const _$ = require('aigle')
_$.mixin(_);

var main = (async function() {
    const collection = [1, 4, 2];

    var result1 = await _$.chain(collection).thru((e) => {
        console.log('do aigle', e);
        return e;
    }).value();
    console.log('aigle result', result1);
//do aigle 1
//do aigle 4
//do aigle 2
//aigle result 1

    var result2 = await _.chain(collection).thru((e) => {
        console.log('do lodash', e);
        return e;
    }).value();
    console.log('lodash result', result2);
//do lodash [ 1, 4, 2 ]
//lodash result [ 1, 4, 2 ]

    var result3 = await _$.chain(collection).then((e) => {
        console.log('do aigle then', e);
        return e;
    }).value();
    console.log('aigle then result', result3);
//do aigle then [ 1, 4, 2 ]
//aigle then result [ 1, 4, 2 ]
})()

**Comment by HoKangInfo** [comment]
`tap` has same question

**Comment by suguru03** [comment]
Thanks for the issue!
Oh, it is a difficult good issue 🤔  
Basically, The `mixin` only covers iterable functions.

I have ideas to solve `thru` and `tap`, but it is difficult to solve all functions automatically. 
ex) `_.intersection`.
I may need to create `aigle-plugin-lodash` to cover all functions, I'll think about it, thank you very much! :)

**Comment by suguru03** [comment]
@HoKangInfo I just fixed and published `v1.10.0`!
If you have any issues, please let me know, thanks! :)
