### ISSUE TITLE
README doc error

### ISSUE THREAD

**Issue by HoKangInfo** [suguru03/aigle#37]
return Aigle.map([1.1, 1.4, 2.2], n => Aigle.delay(10, n * 2)) // [2.2, 2.8, 4.4]
  .uniqBy(n => Aigle.delay(10, Math.floor(n))) // [2.2, 4.4] ==> [2,4]
  .sum() // 6.6 ==> [6]
  .times() // [0, 1, 2, 3, 4, 5];
  .then(value => console.log(value)); // [0, 1, 2, 3, 4, 5];

**Comment by suguru03** [comment]
Thanks for the issue!

It is correct. :)
`uniqBy` returns `[2.2, 4.4]`, not `[2, 4]`, which are original values.
https://lodash.com/docs/4.17.4#uniqBy 

```js
const value = _.chain([1.1, 1.4, 2.2])
  .map(n => n * 2) // [2.2, 2.8, 4.4]
  .uniqBy(n => Math.floor(n)) // [2.2, 4.4]
  .sum() // 6.6 (Actual value is 6.6000000000000005 though..)
  .times() // [0, 1, 2, 3, 4, 5];
  .value();
console.log(value); // [0, 1, 2, 3, 4, 5]
```

Also, I welcome PRs if you find some mistakes. Thanks! 😄

**Comment by HoKangInfo** [comment]
You Are Right!
Should 'return' not 'evaluation'.  @@"

**Comment by suguru03** [comment]
👍
