### ISSUE TITLE
Promise.resolve should consider itself as a promise

### ISSUE THREAD

**Issue by 490844110** [suguru03/aigle#38]
<pre>
<code>
const Aigle = require('aigle');
global.Promise = Aigle
Promise.resolve(Promise.resolve(1)).then(value => console.log('the resolved value is ',value));</code></pre>

The code above will console  
    `the resolved value is  Aigle {
       _resolved: 1,
       _value: 1,
       _key: undefined,
       _receiver: undefined,
       _onFulfilled: undefined,
       _onRejected: undefined,
       _receivers: undefined 
   }`

I think the correct console should be `the resolved value is 1`。

<https://github.com/suguru03/aigle/blob/master/lib/aigle.js#L3633>
should add a judge here
<pre>
<code>
function _resolve(value) {
  if (value instanceof Aigle) {
      return value;
  }
  const promise = new Aigle(INTERNAL);
  promise._resolved = 1;
  promise._value = value;
  return promise;
}
</code>
</pre>

**Comment by suguru03** [comment]
Thanks for the issue!
Oh, I didn't realize the bug, I always welcome PRs, could you send a PR? :)

**Comment by 490844110** [comment]
@suguru03   Thanks for your reply!  I have sent a PR！😄

**Comment by suguru03** [comment]
Thanks!
I merged it! https://github.com/suguru03/aigle/pull/39 :)
