### ISSUE TITLE
reduce in parallel

### ISSUE THREAD

**Issue by Kikobeats** [suguru03/aigle#45]
I note that

```js
aigle
    .reduce(links, iterator, {})
    .then(data => emitter.emit('end', data))
```

resolve the promise in series. Is this intentional?

**Comment by suguru03** [comment]
Yes, it is designed the same as `async.reduce`.
`reduce` is for primitive types such as `number`, `string` and `boolean`. These types can't iterate in parallel.
For reference types, it is better to use `transform` instead. It will work in parallel. :)

```js
aigle
    .transform(links, iterator, {})
    .then(data => emitter.emit('end', data))
```

**Comment by Kikobeats** [comment]
thanks for the tip!

**Comment by Kikobeats** [comment]
Hey @suguru03 one thing, I'm not sure if I can do `transform` preserve the order in the final output, can you confirm? 🙂

**Comment by suguru03** [comment]
Hi @Kikobeats !
`transform` can't ensure the order.
If you want to ensure it, you need to use `transformSeries` or you could use other functions,  such as 
 `map` and `filter`.
`transform` is really flexible, if you elaborate the detail, I could give you a better solution 😺

**Comment by Kikobeats** [comment]
Thanks for the reply!

In general I think the library need more docs (https://github.com/suguru03/aigle/issues/66) for understand the methods. From a newbie perspective they are very similar 🙂

**Comment by suguru03** [comment]
Sure, I completely agree...!
I'm going to prepare new docs and update them, thanks! 🙂
