### ISSUE TITLE
promisify - getBuffer is not a function

### ISSUE THREAD

**Issue by westlakem** [suguru03/aigle#51]
This is in an angular application:

`let uri = await Aigle.promisify(this.carImage.getBase64)(Jimp.MIME_PNG)`

where `this.carImage` is an image from `jimp`

 Results in:

`Error: Uncaught (in promise): TypeError: this.getBuffer is not a function`

**Comment by suguru03** [comment]
It is probably a `this` scope problem. It is the same problem as this code.
```js
const obj = {
  a: 1,
  get() {
    return this.a;
  }
};
console.log(obj.get()); // 1
const get = obj.get;
console.log(get()); // undefined
```

So you need to care about `this` scope, you will be able to re-write as below,
```js
// aigle feature
let uri = await Aigle.promisify(this.carImage, 'getBase64')(Jimp.MIME_PNG)

// bluebird compatibility
let uri = await Aigle.promisify(this.carImage.getBase64, { context: this.carImage })(Jimp.MIME_PNG)

// native promisify style
let uri = await Aigle.promisify(this.carImage.getBase64.bind(this.carImage))(Jimp.MIME_PNG)
```

**Comment by suguru03** [comment]
https://github.com/suguru03/aigle/commit/d846e5a64d2cb0029a4e097354f923b1472fd924
