### ISSUE TITLE
Multiple Asyncs?

### ISSUE THREAD

**Issue by paulxtiseo** [suguru03/aigle#55]
When I use Aigle to `promisifyAll(require('fs'))` I end up with multiple leveled Async functions. For example, for `readFile()` I end up with:

    readFile: [Function],
    readFileAsync: [Function],
    readFileAsyncAsync: [Function],
    readFileAsyncAsyncAsync: [Function],

Path seems to fair worse on almsot all functions:

    resolve: [Function: resolve],
    resolveAsync: [Function],
    resolveAsyncAsync: [Function],
    resolveAsyncAsyncAsync: [Function],
    resolveAsyncAsyncAsyncAsync: [Function],
    resolveAsyncAsyncAsyncAsyncAsync: [Function],
    resolveAsyncAsyncAsyncAsyncAsyncAsync: [Function],
    resolveAsyncAsyncAsyncAsyncAsyncAsyncAsync: [Function]

Why?

PS: `bluebird` does not seem to suffer from this. I get one Async promise-returning function for each function in a library.

**Comment by suguru03** [comment]
Thank you for the issue!
I reproduced it, it is a bug. 😢 
If `promisifyAll` is called multiple times, the function creates new functions, I'm gonna fix it, thanks!

**Comment by suguru03** [comment]
It is fixed. I'm gonna release it on v.1.12 😄

**Comment by paulxtiseo** [comment]
Is it part of 1.12.0-alpha.2?

**Comment by paulxtiseo** [comment]
Sorry, but a followup Q: any ballpark idea on when v1.12 will be released?

**Comment by suguru03** [comment]
I'm gonna release it on `v1.12.0-alpha.3` today. :)
I was planning to release https://github.com/suguru03/aigle/issues/22 on `v1.12`, but I will take time more. So, I'm gonna move it to `v1.13` and release `v1.12` sometime soon. 😄

**Comment by suguru03** [comment]
I published `v1.12.0-alpha.3` 😄
