### ISSUE TITLE
Could I test `Aigle` on JsFiddle?

### ISSUE THREAD

**Issue by thearabbit** [suguru03/aigle#64]
Could I test `Aigle` on JsFiddle?
Please help me

**Comment by suguru03** [comment]
Thanks for the issue!
It seems like a tool for UI testing. 

I could host it to the Aigle document page instead.
I hosted some libraries to [gh-pages](https://suguru03.github.io/libweb/) to test on Chrome console, you could also use it. 🙂

**Comment by thearabbit** [comment]
Thanks I will try
