### ISSUE TITLE
Typescript returns Aigle as undefined

### ISSUE THREAD

**Issue by saachinsiva** [suguru03/aigle#67]
Hello
I am not sure if typescript is fully completed but when I try to import Aigle as mentioned in the doc, I am getting Aigle as undefined which fails all my calls. E.g. Agile.eachLimit throws an error 'Cannot read propery eachLimit of undefined'. However the below code works fine.

import * as Aigle from 'aigle'
then Aigle.default.eachLimit

**Comment by suguru03** [comment]
Hi @saachinsiva ! 
Thanks for the issue! 🙂 

Can you try to import as below?

```ts
import Aigle from 'aigle';
// or
import { Aigle } from 'aigle';

// not
import * as Aigle from 'aigle';
```

**Comment by saachinsiva** [comment]
Hello

Thanks for getting back to me. But as I said earlier, I did try that and both returns Aigle as undefined. I believe Aigle is not instantiated . E.g.

```
import { Aigle } from 'aigle';

export class AigleTest {

    testMethod() {
        Aigle.each([1, 2, 3, 4, 5], (item) => {
            console.log(item);
        });
    }
}

new AigleTest().testMethod()
```

Running above code produces : (Its the same result if I do import Aigle from 'aigle';)
```
C:\StashRepo\InstantQuote_V4\server\src\test.ts:6
        Aigle.each([1, 2, 3, 4, 5], (item) => {
              ^
TypeError: Cannot read property 'each' of undefined
    at AigleTest.testMethod (C:\StashRepo\InstantQuote_V4\server\src\test.ts:6:15)
    at Object.<anonymous> (C:\StashRepo\InstantQuote_V4\server\src\test.ts:12:17)
    at Module._compile (module.js:652:30)
    at Module.m._compile (C:\Users\smasilamani\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:400:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\smasilamani\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:403:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

But if I use the namespace like this, then it works

```
import * as Aigle from 'aigle';

export class AigleTest {

    testMethod() {
        Aigle.default.each([1, 2, 3, 4, 5], (item) => {
            console.log(item);
        });
    }
}

new AigleTest().testMethod();
```

Output : 
```
C:\StashRepo\InstantQuote_V4\server>ts-node .\src\test.ts
1
2
3
4
5
```

**Comment by suguru03** [comment]
Thanks for the reply and the report detail. 
I have reproduced it, the issue is that `import { Aigle } from 'aigle';` not working properly.
Could you use `import Aigle from 'aigle'` instead for now? I'm going to fix it ASAP.
Sorry for the inconvenience. 😢

**Comment by saachinsiva** [comment]
Thanks. As of now I am using import Aigle from 'aigle'.

**Comment by suguru03** [comment]
@saachinsiva 
I fixed it on `v1.13.0-alpha-8`. Could you try it?

**Comment by saachinsiva** [comment]
Thanks it worked now.

**Comment by suguru03** [comment]
Thanks! 😄
