### ISSUE TITLE
Object.assign found in aigle-es5.min.js

### ISSUE THREAD

**Issue by FrivalszkyP** [suguru03/aigle#80]
I found that the aigle-es5.min.js in the npm package contains Object.assign even though it was only introduced with ES6/ES2015. Also, despite its min.js name, the file is not minified. Can you please look into these? Thank you!

**Comment by FrivalszkyP** [comment]
Deleting this as I realized that polyfills are a different beast and they should not be taken care of here. :)

**Comment by suguru03** [comment]
@FrivalszkyP Thanks for using it! 😄 
If you find any issues, please feel free to let me know!
