### ISSUE TITLE
Add flow method

### ISSUE THREAD

**Issue by Kikobeats** [suguru03/aigle#82]
Hello,

I noted async [flow](https://lodash.com/docs/4.17.11#flow) method is missing.

It's very useful and implementation is pretty simple:

```js
const asyncFlow = fns => data =>
  aigle.reduce(fns, (acc, fn) => fn(data, acc), data)
```

Happy to make a PR if you are going to accept it.

Related with https://github.com/suguru03/aigle/issues/70

**Comment by suguru03** [comment]
@Kikobeats Thanks for the suggestion, I think it is really useful! 😄 
I welcome the PR! If you need to help it, please let me know!

**Comment by Kikobeats** [comment]
well I tried but it was impossible to me understand the code :((

**Comment by suguru03** [comment]
True, it is really difficult. I'll take a look. 👀

**Comment by suguru03** [comment]
```js
const add = function(a, b) {
  return Aigle.delay(10, a + b);
};

const square = function(n) {
  return Aigle.delay(10, n * n);
};

Aigle.flow = ([fn, ...fns]) => (...data) =>
  Aigle.resolve(fn(...data)).then(data => Aigle.reduce(fns, (acc, fn) => fn(data, acc), data));

const addSquare = Aigle.flow([add, square]);
addSquare(1, 2).then(console.log);
```

I added the first function handling.
The arguments seem to be `...(function|function[])`, we need to handle it. 🤔 
https://lodash.com/docs/4.17.11#flow

I don't think we need the instance function, so you can simply add it as a class function 😄

**Comment by suguru03** [comment]
Done :)

**Comment by Kikobeats** [comment]
awesome 🎉
