### ISSUE TITLE
Update benchmarks for latest node versions

### ISSUE THREAD

**Issue by bompus** [suguru03/aigle#91]
Would you be able to re-run the benchmarks and update them to reflect how fast Aigle is and how it compares to native-async-await in both Node 10.x and Node 11.x

I believe there have been significant performance improvements with Promises in 10.x and probably even faster in 11.x, but we don't know until it is tested.

**Comment by suguru03** [comment]
Thanks for the issue! I updated the [benchmark result](https://github.com/suguru03/aigle/tree/master/benchmark)!

The native Promise is really faster than before, it is really great!
For the next step, I'm planning to support the native one as well 😉
